global:
  scrape_interval:     5s
  evaluation_interval: 30s

  external_labels:
    monitor: cortex-test

rule_files:
  - "rules/*"

scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: rabbitmq
    metrics_path: /api/metrics
    static_configs:
      - targets: ['rabbitmq:15672']
  - job_name: sftp-scanner
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.42.51:56009']

remote_write:
  - url: "http://adapter:9201/write"

remote_read:
  - url: "http://adapter:9201/read"
