[package]
name = "cortex"
version = "0.1.0"
authors = ["Alfred Blokland <alfred.blokland@hendrikx-itc.nl>"]

[dependencies]
inotify = "0.6"
serde = "1.0"
serde_derive = "1.0"
config = "0.9"
regex = "1"
serde_regex = "0.3"
