[workspace]
members = [
    "dev-stack",
    "sftp-scanner",
    "core",
    "dispatcher",
    "integration-tests",
]
resolver = "2"

[workspace.package]
version = "1.6.1"
authors = ["1Optic B.V. <info@1optic.io>"]
edition = "2021"
license = "GPL-3.0-or-later"
