[package]
name = "cortex-dispatcher"
version = "0.1.2"
authors = ["Alfred Blokland <alfred.blokland@hendrikx-itc.nl>"]
edition = "2018"
description = """
Cortex is system for efficiently collecting and distributing files with a
choice of multiple protocols
"""
license = "GPL-3.0-or-later"
documentation = "https://cortex-dispatcher.readthedocs.io/en/latest/"
homepage = "https://github.com/hendrikx-itc/cortex-dispatcher"
repository = "https://github.com/hendrikx-itc/cortex-dispatcher"

[dependencies]
log = "0.4"
env_logger = "0.6.1"
inotify = "0.7"
serde = "1.0"
serde_derive = "1.0"
config = "0.9"
regex = "1"
serde_regex = "0.3"
clap = "2.33"
ssh2 = "0.3.3"
futures = "0.1"
lapin-async = "0.18.0"
lapin-futures = "0.18.0"
tokio = "0.1.19"
tokio-executor = "0.1"
failure = "0.1.5"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.8"
tee = "0.1"
prometheus = { version = "0.6", features = ["push"] }
lazy_static = "1.3"
postgres = "0.15.2"
cortex-core = { path = "../core" }
crossbeam-channel = "0.3"
