[package]
name = "cortex-dispatcher"
version = "0.1.45"
authors = ["Alfred Blokland <alfred.blokland@hendrikx-itc.nl>"]
edition = "2018"
description = """
Cortex is system for efficiently collecting and distributing files with a
choice of multiple protocols
"""
license = "GPL-3.0-or-later"
documentation = "https://cortex-dispatcher.readthedocs.io/en/latest/"
homepage = "https://github.com/hendrikx-itc/cortex-dispatcher"
repository = "https://github.com/hendrikx-itc/cortex-dispatcher"

[package.metadata.deb]
assets = [
    ["target/release/cortex-dispatcher", "/usr/bin/", "755"],
    ["static-web/*", "/usr/lib/cortex/static-web/", "644"]
]

[target.'cfg(target_os = "linux")'.dependencies]
inotify = "0.7"

[dependencies]
log = "0.4"
env_logger = "0.6"
serde = "1.0"
serde_derive = "1.0"
config = "0.9"
regex = "1.2"
serde_regex = "0.4"
clap = "2"
ssh2 = "0.4"
futures = "0.1"
lapin = "0.26"
lapin-futures = "0.26"
tokio = "0.1"
tokio-executor = "0.1"
failure = "0.1"
failure_derive = "0.1"
serde_json = "1.0"
serde_yaml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.8"
tee = "0.1"
prometheus = { version = "0.7", features = ["push"] }
lazy_static = "1.3"
postgres = "0.16.0-rc.2"
tokio-postgres = "0.4.0-rc.3"
cortex-core = { path = "../core" }
crossbeam-channel = "0.3"
actix-web = "1.0"
actix-files = "0.1"
actix-rt = "0.2"
actix-http = "0.2"
r2d2 = "0.8"
r2d2_postgres = "0.15.0-rc.1"
tera = "0.11"
signal-hook = { version = "0.1.10", features = ["tokio-support"] }
retry = "0.5"
proctitle = "0.1"
error-chain = "0.12"
tokio-retry = "0.2"
